import Head from "next/head";
import { useEffect, useState } from "react";
import { useDebounce } from "@myapp/hooks";
import styles from "../styles/Home.module.css";

export default function Home() {
  const [mouseOnFirstBox, setMouseOnFirstBox] = useState(false);
  const [mouseOnSecondBox, setMouseOnSecondBox] = useState(false);
  const [firstBoxText, setFirstBoxText] = useState("NOT hovering");
  const [secondBoxText, setSecondBoxText] = useState(
    "NOT hovering (debounced)"
  );

  const debouncedMouseOnSecondBox = useDebounce(mouseOnSecondBox, 500);

  useEffect(() => {
    setFirstBoxText(mouseOnFirstBox ? "Hovering!" : "NOT Hovering");
  }, [mouseOnFirstBox]);

  useEffect(() => {
    setSecondBoxText(
      debouncedMouseOnSecondBox
        ? "Hovering! (debounced)"
        : "NOT Hovering (debounced)"
    );
  }, [debouncedMouseOnSecondBox]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div
          className={styles.box}
          onMouseEnter={() => setMouseOnFirstBox(true)}
          onMouseLeave={() => setMouseOnFirstBox(false)}
        >
          <h1>{firstBoxText}</h1>
        </div>

        <div
          className={styles.box}
          onMouseEnter={() => setMouseOnSecondBox(true)}
          onMouseLeave={() => setMouseOnSecondBox(false)}
        >
          <h1>{secondBoxText}</h1>
        </div>
      </main>
    </div>
  );
}
